# Generated by Django 3.2.4 on 2021-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_title', models.CharField(max_length=255)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('assignment_progress', models.BooleanField(default=False)),
            ],
        ),
    ]
